# Full reference: https://docs.airplane.dev/tasks/task-definition

# Used by Airplane to identify your task. Do not change.
slug: demo_create_linear_issue

# A human-readable name for your task.
name: Create Linear Issue

# A human-readable description for your task.
# description: "My Airplane task"

# A list of inputs to your task.
parameters:
  - slug: title
    # A human-readable name for the parameter.
    name: Title
    # The type of parameter. Valid values: shorttext, longtext, sql, boolean,
    # upload, integer, float, date, datetime, configvar.
    type: shorttext
    # A human-readable description of the parameter.
    description: The title of the linear issue
    # Set to false to indicate that this parameter. is optional. Default: true.
    required: true
    # A list of options to constrain the parameter values. For configvar types,
    # each option needs to be an object with a label (value to show to user) and
    # a config (name of the config var). For all other types, each option can be
    # a single value or an object with a label and a value.
    # A regular expression with which to validate parameter values.
  - slug: team_id
    # A human-readable name for the parameter.
    name: Team ID
    # The type of parameter. Valid values: shorttext, longtext, sql, boolean,
    # upload, integer, float, date, datetime, configvar.
    type: shorttext
    # A human-readable description of the parameter.
    description: The team ID for the linear issue
    # Set to false to indicate that this parameter. is optional. Default: true.
    required: true
  - slug: assignee_id
    # A human-readable name for the parameter.
    name: Assignee ID
    # The type of parameter. Valid values: shorttext, longtext, sql, boolean,
    # upload, integer, float, date, datetime, configvar.
    type: shorttext
    # A human-readable description of the parameter.
    description: The ID of the assignee for the linear issue
    # Set to false to indicate that this parameter. is optional. Default: true.
    required: true
  - slug: description
    # A human-readable name for the parameter.
    name: Description
    # The type of parameter. Valid values: shorttext, longtext, sql, boolean,
    # upload, integer, float, date, datetime, configvar.
    type: longtext
    # A human-readable description of the parameter.
    description: The description for the linear issue
    # Set to false to indicate that this parameter. is optional. Default: true.
    required: false
  - slug: priority
    # A human-readable name for the parameter.
    name: Priority
    # The type of parameter. Valid values: shorttext, longtext, sql, boolean,
    # upload, integer, float, date, datetime, configvar.
    type: integer
    # A human-readable description of the parameter.
    description: The priority of the linear issue
    # Set to false to indicate that this parameter. is optional. Default: true.
    required: false
    options:
      - label: No Priority
        value: 0
      - label: Urgent
        value: 1
      - label: High
        value: 2
      - label: Medium
        value: 3
      - label: Low
        value: 4

# Configuration for a Node task.
node:
  # The path to the .ts or .js file containing the logic for this task. This
  # can be absolute or relative to the location of the definition file.
  entrypoint: create_linear_issue.ts

  # The version of Node to use. Valid values: 14, 16, 18.
  nodeVersion: "18"

  # A map of environment variables to use when running the task. The value
  # should be an object; if specifying raw values, the value must be an object
  # with `value` mapped to the value of the environment variable; if
  # using config variables, the value must be an object with `config`
  # mapped to the name of the config variable.
  envVars:
    LINEAR_API_KEY:
      config: LINEAR_API_KEY
# Set label constraints to restrict this task to run only on agents with
# matching labels.
# constraints:
#   aws-region: us-west-2

# Set to true to disable direct execution of this task. Default: false.
# requireRequests: true

# Set to false to disallow requesters from approving their own requests for
# this task. Default: true.
# allowSelfApprovals: false

# The maximum number of seconds the task should take before being timed out.
# Default: 3600.
# timeout: 1800
