# Full reference: https://docs.airplane.dev/tasks/task-definition

slug: demo_list_linear_users
name: List Linear Users

node:
  entrypoint: list_linear_users.ts
  nodeVersion: "18"
  envVars:
    LINEAR_API_KEY:
      config: LINEAR_API_KEY
