FROM ubuntu:22.04

WORKDIR /app

# install AWS cli tools
RUN apt-get update && \
    apt-get install -y awscli

# install mongodb tools including mongodump
RUN apt-get update && \
    apt-get install -y mongodb-clients

