# Dockerfile.airplane
FROM ruby:2.6

WORKDIR /app
# Apply your Gem dependencies if it exists
# COPY Gemfile /app/Gemfile
# COPY Gemfile.lock /app/Gemfile.lock
# RUN bundle install --deployment

COPY task.rb .
