slug: search_users
name: Search users
description: "Search for users in prod based on team and user info"
parameters:
  - slug: query
    name: Query
    type: shorttext
    default: ""
sql:
  resource: "DB"
  entrypoint: search_users.sql

  queryArgs:
    search: "%{{params.query}}%"
